# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_imagedialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ImageDialog(object):
    def setupUi(self, Ui_ImageDialog):
        Ui_ImageDialog.setObjectName("Ui_ImageDialog")
        Ui_ImageDialog.resize(400, 254)
        Ui_ImageDialog.setWindowTitle("Abrir Arquivo")
        self.buttonBox = QtWidgets.QDialogButtonBox(Ui_ImageDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 220, 361, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.listView = QtWidgets.QListView(Ui_ImageDialog)
        self.listView.setGeometry(QtCore.QRect(10, 30, 381, 181))
        self.listView.setObjectName("listView")
        self.label = QtWidgets.QLabel(Ui_ImageDialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 47, 13))
        self.label.setObjectName("label")

        self.retranslateUi(Ui_ImageDialog)
        self.buttonBox.accepted.connect(Ui_ImageDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Ui_ImageDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Ui_ImageDialog)

    def retranslateUi(self, Ui_ImageDialog):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("Ui_ImageDialog", "Arquivos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_ImageDialog = QtWidgets.QDialog()
    ui = Ui_ImageDialog()
    ui.setupUi(Ui_ImageDialog)
    Ui_ImageDialog.show()
    sys.exit(app.exec_())
